# Generated by Django 3.2.5 on 2021-10-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_donation_already_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='already_received',
            field=models.BooleanField(default=False),
        ),
    ]
