# Generated by Django 3.2.5 on 2021-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_donation_already_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
